name: green3neo
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  data_table_2: ^2.7.2
  ffi: ^2.0.2
  file_picker: ^10.3.8
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_rust_bridge: ^2.11.1
  freezed_annotation: ^3.1.0
  get_it: ^9.2.0
  listen_it: ^5.3.4
  watch_it: ^2.4.1
  intl: ^0.20.2
  logging: ^1.3.0
  pair: ^0.1.2
  path_provider: ^2.1.5
  provider: ^6.1.1
  reflectable: ^4.0.5
  window_manager: ^0.5.1

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  ffigen: ^19.1.0
  freezed: ^3.0.6

flutter:
  uses-material-design: true
  generate: true
