[package]
name = "sepa_types"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["rlib"]

[dependencies]
chrono = { version = "^0.4.42", features = ["alloc", "unstable-locales"] }
serde = { version = "1.0.228", features = ["derive"] }
