[package]
name = "backend_testing"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["rlib"]

[dependencies]
backend_logging = { path = "../backend_logging" }
speculoos = "0.11.0"
flexi_logger = { version = "0.29.8", features = [
    "async",
    "colors",
    "specfile",
] }
log = "0.4.25"
